---
- name: Testing andrewrothstein.timoni
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'timoni --version'
      ansible.builtin.command: timoni --version
      changed_when: false
      register: timoni_test_output
    - name: Output from 'timoni --version'
      ansible.builtin.debug:
        msg: '{{ timoni_test_output.stdout }}'
