---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/timoni --version
      register: timoni_test_output
    - name: timoni --version
      debug:
        msg: '{{ timoni_test_output.stdout }}'
