---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ timoni_install_exe }}
  ansible.builtin.stat:
    path: '{{ timoni_install_exe }}'
  register: timoni_binary
- name: Downloading and installing timoni
  when: not timoni_binary.stat.exists
  block:
    - name: Downloading {{ timoni_url }} to {{ timoni_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ timoni_url }}'
        dest: '{{ timoni_tmp_archive }}'
        checksum: '{{ timoni_checksum }}'
        mode: '644'
    - name: Mkdir {{ timoni_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ timoni_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive {{ timoni_tmp_archive }} to {{ timoni_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ timoni_tmp_archive }}'
        dest: '{{ timoni_install_dir }}'
        creates: '{{ timoni_install_exe }}'
  always:
    - name: Rm {{ timoni_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ timoni_tmp_archive }}'
        state: absent
- name: Link {{ timoni_link }} to {{ timoni_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ timoni_install_exe }}'
    dest: '{{ timoni_link }}'
    state: link
