---
- include_role:
    name: andrewrothstein.unarchivedeps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ timoni_install_exe }}
  stat:
    path: '{{ timoni_install_exe }}'
  register: timoni_binary
- when: not timoni_binary.stat.exists
  block:
    - name: downloading {{ timoni_url }} to {{ timoni_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ timoni_url }}'
        dest: '{{ timoni_tmp_archive }}'
        checksum: '{{ timoni_checksum }}'
        mode: 0644
    - name: mkdir {{ timoni_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ timoni_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ timoni_tmp_archive }} to {{ timoni_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ timoni_tmp_archive }}'
        dest: '{{ timoni_install_dir }}'
        creates: '{{ timoni_install_exe }}'
  always:
    - name: rm {{ timoni_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ timoni_tmp_archive }}'
        state: absent
- name: link {{ timoni_link }} to {{ timoni_install_exe }}
  become: true
  become_user: root
  file:
    src: '{{ timoni_install_exe }}'
    dest: '{{ timoni_link }}'
    state: link
